#! /usr/bin/env sh

list_parsers() {
  langs=$(cut -d ':' -f 1 ref)
  directories=""
  for item in $langs; do
    if [ -d "$item" ]; then
      directories="$directories $item"
    fi
  done
  echo "$directories"
}

directories_to_delete=$(list_parsers)

if [ -z "$directories_to_delete" ]; then
  echo "Nothing to clean."
  exit 0
fi

# Ask for confirmation
echo "Cleaning:"
echo ""
for dir in $directories_to_delete; do
  echo "  $dir/"
done
echo ""

read -p "Do you really want to delete these parsers? (y/n) " choice

case "$choice" in
  y|Y ) 
    for dir in $directories_to_delete; do
      rm -rf "$dir"
      echo "Deleted $dir"
    done
    ;;
  n|N )
    echo "No directories were deleted."
    ;;
  * )
    echo "Invalid choice. No directories were deleted."
    ;;
esac

