name: cd

on: [push]

jobs:
  build:
    strategy:
     fail-fast: false
     matrix:
       os: [ubuntu, macos]
       lang:
         # - c
         # - cpp
         # - java
         - javascript
         # - ruby
         # - rust
    runs-on: ${{ matrix.os }}
    steps:
      - name: Build ${{ matrix.lang }}
        run: |
          ./lang ${{ matrix.lang }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          files: |
            ./lib/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
