name: cd

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - v[0-9]+.[0-9]+

jobs:
  build:
    name: ${{ matrix.platform }} (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux-x64
          - macos-arm64

        include:
          - { platform: linux-x64, os: ubuntu-latest }
          - { platform: macos-arm64, os: macos-14 }
    runs-on: ${{ matrix.os }}
    env:
      PLATFORM: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Download tsdl
        run: |
          curl -o tsdl.gz -L "https://github.com/stackmystack/tsdl/releases/latest/download/tsdl-${{ matrix.platform }}.gz"
          gunzip tsdl.gz
          chmod +x tsdl
      - name: Build
        run: |
          ./tsdl build --out-dir lib/${{ matrix.platform}}
      - name: Prepare git # To get tags from `git describe`
        run: |
          git fetch --prune --unshallow
      - name: Make .deb
        if: matrix.os == 'ubuntu-latest'
        run: |
          ./package/deb
      - name: Make zip and tar
        run: |
          ./package/zip
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.vars.outputs.sha_short }}
          name: Release ${{ github.ref }}-${{ steps.vars.outputs.sha_short }}
          draft: true
          files: |
            ./lib/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
