name: cd

on: [push]

jobs:
  build-ubuntu:
    strategy:
     fail-fast: false
     matrix:
       lang:
         - c
         # - cpp
         # - java
         # - javascript
         # - ruby
         # - rust
       triplet:
         - x86_64-linux-gnu
         - arm-linux-gnueabi
         - arm-linux-gnueabihf
         - aarch64-linux-gnu
         - mipsel-linux-gnu
         - powerpc64le-linux-gnu
         #
         # FIXME: tree-sitter has a known (by me) bug by now:
         #          ld: unknown option -soname
         # It should be patched to support
         # - x86_64-apple-darwin
         # - x86_64h-apple-darwin
         # - i386-apple-darwin
         - x86_64-w64-mingw32
         - i686-w64-mingw32
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build ${{ matrix.lang }} for ${{ matrix.triplet }}
        run: |
          docker run --rm -v $(pwd):/workdir -e CROSS_TRIPLE=${{ matrix.triplet }} multiarch/crossbuild  ./lang ${{ matrix.lang }}
      - name: Build ${{ matrix.lang }} for macos
        if: ${{ matrix.os == 'macos' }}
        run: |
          ./lang ${{ matrix.lang }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.vars.outputs.sha_short }}
          release_name: Release ${{ github.ref }}-${{ steps.vars.outputs.sha_short }}
          draft: true
          files: |
            ./lib/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    strategy:
     fail-fast: false
     matrix:
       lang:
         - c
         # - cpp
         # - java
         # - javascript
         # - ruby
         # - rust
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build ${{ matrix.lang }} for macos
        run: |
          ./lang ${{ matrix.lang }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.vars.outputs.sha_short }}
          release_name: Release ${{ github.ref }}-${{ steps.vars.outputs.sha_short }}
          draft: true
          files: |
            ./lib/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
