name: cd

on: [push]

jobs:
  build:
    strategy:
     fail-fast: false
     matrix:
       target:
          - { os: ubuntu-latest, platform: linux-x64 }
          - { os: macos-latest, platform: macos-arm64 }
    runs-on: ${{ matrix.target.os }}
    env:
      PLATFORM: ${{ matrix.target.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Build for ${{ matrix.target.platform }}
        run: |
          ./lang d bash c embedded-template html java javascript json python ruby rust
      - name: Prepare git # To get tags from `git describe`
        run: git fetch --prune --unshallow
      - name: Make .deb
        if: matrix.target.os == 'ubuntu-latest'
        run: |
          ./package/deb
      - name: Make zip and tar
        run: |
          ./package/zip
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.vars.outputs.sha_short }}
          name: Release ${{ github.ref }}-${{ steps.vars.outputs.sha_short }}
          draft: true
          files: |
            ./lib/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-fixed-assets:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare git # To get tags from `git describe`
        run: git fetch --prune --unshallow
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.vars.outputs.sha_short }}
          name: Release ${{ github.ref }}-${{ steps.vars.outputs.sha_short }}
          draft: true
          files: ref
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
