name: cd

on: [push]

jobs:
  build:
    strategy:
     fail-fast: false
     matrix:
       lang:
         - c
         # - cpp
         # - java
         # - javascript
         # - ruby
         # - rust
       triplet:
         - x86_64-linux-gnu
         - arm-linux-gnueabi
         - arm-linux-gnueabihf
         - aarch64-linux-gnu
         - mipsel-linux-gnu
         - powerpc64le-linux-gnu
         - x86_64-apple-darwin
         - x86_64h-apple-darwin
         - i386-apple-darwin
         - x86_64-w64-mingw32
         - i686-w64-mingw32
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build ${{ matrix.lang }} for ${{ matrix.triplet }}
        run: |
          docker run --rm -v $(pwd):/workdir -e CROSS_TRIPLE=${{ matrix.triplet }} multiarch/crossbuild  ./lang ${{ matrix.lang }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          files: |
            ./lib/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
